[package]
name = "ntex-mqtt"
version = "0.6.7"
authors = ["ntex contributors <team@ntex.rs>"]
description = "MQTT Client/Server framework for v5 and v3.1.1 protocols"
documentation = "https://docs.rs/ntex-mqtt"
repository = "https://github.com/ntex-rs/ntex-mqtt.git"
categories = ["network-programming"]
keywords = ["MQTT", "IoT", "messaging"]
license = "MIT"
exclude = [".gitignore", ".travis.yml", ".cargo/config"]
edition = "2018"

[features]
pass-control = []

[dependencies]
ntex = { version = "0.3.17", default-features = false }
bitflags = "1.2.1"
derive_more = "0.99"
log = "0.4"
serde = "1.0"
serde_json = "1.0"
pin-project-lite = "0.2.5"

[dev-dependencies]
env_logger = "0.8"
futures = "0.3"
rustls = "0.19"
tokio-rustls = "0.22"
openssl = "0.10"
tokio-openssl = "0.6"

ntex = { version = "0.3.17", features = ["rustls", "openssl"] }
